### ISSUE TITLE
Update Activity Pub comments to use fqUsername when available

### ISSUE THREAD

**Issue by stevencrader** [podverse/podverse-shared#2]
For Activity Pub comments, the user ID is used instead of the fqUsername. This results in the user's comment being attributed to a random string instead of their real username. 

This was originally reported here: https://podcastindex.social/@boobury/111727513459359089

It looks like it could be fixed by using the `fqUsername` from the `commenters` when available. 

Code area:

https://github.com/podverse/podverse-shared/blob/71f9770c920bd5f8e3c8adbcfb43a9e7a5673800/src/socialInteraction/Threadcap.ts#L63-L70

Example of API return:

![api_example](https://github.com/podverse/podverse-shared/assets/677342/299c6a0d-d275-4c89-9b8d-10732174ee7f)

**Comment by mitchdowney** [comment]
Finally getting back in the saddle with Podverse development...this should be fixed in Podverse mobile 4.16.0. Thanks for the proposed fix! I pushed it to a new branch as I borked the existing develop branch.

https://github.com/podverse/podverse-shared/commit/b082e2a4440854b377a544ac612c87f924e3615f

Considering embarking on a full rewrite of everything for v5 soon 😵
